import 'package:flutter/foundation.dart';

class AppStrings {
  static final ValueNotifier<String> locale = ValueNotifier('bs');

  static const Map<String, Map<String, String>> _values = {
    'bs': {
      'device': 'Uređaji', 'care': 'Njega', 'services': 'Servisi', 'me': 'Ja',
      'my_cats': 'Moje mačke', 'add': 'Dodaj', 'server_address': 'Adresa servera',
      'notifications': 'Notifikacije', 'notifications_sub': 'Podsjetnici i upozorenja o niskom nivou',
      'about_app': 'O aplikaciji', 'about_app_sub': 'Verzija, licenca, o projektu',
      'language': 'Jezik', 'bosnian': 'Bosanski', 'english': 'Engleski',
      'online': 'Online', 'food': 'Hrana', 'water': 'Voda', 'temperature': 'Temperatura',
      'tap_for_status': 'Dodirni za detaljan status →', 'discover': 'Otkrij',
      'connect_camera': 'Poveži kameru na hranilicu', 'connect_camera_sub': 'Nadgledaj svoju mačku uživo, bilo gdje.',
      'coming_soon': 'Uskoro', 'not_connected': 'Nije povezano',
      'camera_not_connected': 'Kamera nije povezana',
      'camera_explain': 'Uživo snimak treba ESP32-CAM modul i streaming server, koji još nisu dio hardvera. Kad se to poveže, ovdje ćeš uparivati kameru i gledati mačku uživo.',
      'understand': 'Razumijem',
      'feeder_name': 'CatFeeder Hranilica',
      'feeding_schedule': 'Raspored hranjenja i evidencija', 'feeding_schedule_sub': 'Podesi automatsko hranjenje i pregledaj historiju',
      'store': 'Prodavnica', 'store_sub': 'Hrana, dodaci i oprema',
      'no_cats_yet': 'Nemaš još nijednu mačku.', 'user': 'Korisnik',
      'dashboard': 'Pregled', 'care_list': 'Lista njege', 'overview': 'Statistika', 'edit': 'Uredi',
      'weight': 'Težina', 'food_intake': 'Unos hrane', 'meals': 'Obroci', 'total': 'Ukupno',
      'water_level': 'Nivo vode', 'current': 'Trenutno', 'status': 'Status', 'low': 'Nisko',
      'ok': 'U redu', 'trend_7d': '7-dnevni trend',

      'coming_soon_snackbar': 'Uskoro dostupno.',
      'times_suffix': 'puta', 'about_cat': 'O mački', 'years_suffix': 'god.',
      'male': 'Mužjak', 'female': 'Ženka',
      'no_cat_dashboard': 'Dodaj svoju prvu mačku da vidiš dashboard.',
      'no_cat_care_list': 'Dodaj svoju prvu mačku da vidiš listu njege.',
      'todo': 'Zadaci', 'daily_progress': 'Dnevni napredak', 'add_task': 'Dodaj zadatak',
      'eg_half_cup': 'npr. 1/2 šolje', 'cancel': 'Otkaži', 'save': 'Sačuvaj', 'delete': 'Obriši',

      'edit_profile': 'Uredi profil', 'add_cat_title': 'Dodaj mačku',
      'save_changes_failed': 'Nije uspjelo čuvanje izmjena.', 'add_cat_failed': 'Nije uspjelo dodavanje mačke.',
      'delete_cat_q': 'Obrisati',
      'delete_cat_warning': 'Ovo će trajno obrisati i historiju hranjenja i rasporede. Ne može se poništiti.',
      'delete_failed': 'Brisanje nije uspjelo.',
      'cat_name_label': 'Ime mačke', 'eg_bella': 'npr. Bella', 'gender_label': 'Spol',
      'age_label': 'Godine', 'weight_kg_label': 'Težina (kg)', 'breed_label': 'Rasa',
      'eg_domestic_shorthair': 'Domaća kratkodlaka', 'save_changes': 'Sačuvaj izmjene',
      'delete_cat_button': 'Obriši mačku', 'unknown_breed': 'Nepoznata rasa',
      'daily_goal_label': 'Dnevni cilj hrane',
      'notif_feeding_title': 'Vrijeme za hranjenje 🐾',
      'notif_feeding_body_needs': 'treba',
      'notif_food_low_title': 'Ponestaje hrane! 🍽️',
      'notif_water_low_title': 'Ponestaje vode! 💧',
      'notif_level_food_word': 'Nivo hrane',
      'notif_level_water_word': 'Nivo vode',
      'notif_level_body_suffix': 'je pao na',
      'notif_level_body_action': 'Vrijeme je da dosuješ.',
      'notif_schedule_channel_name': 'Podsjetnici za hranjenje',
      'notif_schedule_channel_desc': 'Podsjeća te kad je vrijeme za zakazano hranjenje',
      'notif_alert_channel_name': 'Upozorenja o nivou',
      'notif_alert_channel_desc': 'Upozorava kad ponestane hrane ili vode',
      'version_label': 'Verzija', 'close_button': 'Zatvori',
      'edit_name_title': 'Tvoje ime', 'your_name_hint': 'npr. Asad',
      'welcome_subtitle': 'Brižna njega za tvoju mačku, na dohvat ruke.',
      'your_name_question': 'Kako se zoveš?', 'continue_button': 'Nastavi',
      'logout': 'Odjava', 'logout_confirm_title': 'Odjaviti se?',
      'logout_confirm_body': 'Tvoje ime će biti obrisano. Mačke, rasporedi i adresa servera ostaju sačuvani.',
      'create_account_subtitle': 'Napravi nalog da počneš.',
      'username_label': 'Korisničko ime', 'password_label': 'Lozinka',
      'password_hint_min': 'Bar 6 karaktera.',
      'create_account_button': 'Napravi nalog', 'login_button': 'Prijava',
      'have_account_question': 'Već imaš nalog? Prijavi se',
      'no_account_question': 'Nemaš nalog? Napravi ga',

      'server_url_invalid': 'Adresa mora početi sa http:// ili https://',
      'connection_success': 'Konekcija uspješna! Server odgovara.',
      'connection_error_status': 'Server je odgovorio, ali sa greškom',
      'connection_failed_prefix': 'Ne mogu da se povežem: ',
      'address_saved': 'Adresa sačuvana i podaci osvježeni. 🐾',
      'backend_address_title': 'Adresa backend servera',
      'backend_address_sub': 'Ovdje app zna gdje da traži tvoj .NET backend.',
      'test_connection': 'Testiraj konekciju',
      'hide_help': 'Sakrij pomoć', 'which_address': 'Koju adresu staviti?',
      'help_emulator_label': '• Android Emulator (testiranje na računaru):',
      'help_real_phone_label': '• Pravi telefon, ista WiFi mreža kao računar:',
      'help_lan_ip_note': '(LAN IP nađeš sa "ipconfig" u terminalu, na primjer 192.168.1.50)',

      'unknown_cat': 'Nepoznata mačka', 'error_reading_history_prefix': 'Greška pri čitanju istorije: ',
      'delete_schedule_q': 'Obriši raspored?', 'action_irreversible': 'Ova akcija se ne može poništiti.',
      'error_prefix': 'Greška: ', 'activities_title': 'Aktivnosti',
      'history_tab': 'Historija', 'schedules_tab': 'Rasporedi', 'new_schedule': 'Novi raspored',
      'no_feedings_logged': 'Nema zabilježenih hranjenja',
      'no_feedings_logged_sub': 'Čim nahraniš mačku (ručno ili preko rasporeda), pojaviće se ovdje.',
      'no_schedules': 'Nema rasporeda',
      'no_schedules_sub': 'Zakaži automatsko hranjenje po danima u sedmici i tačnom vremenu.',
      'triggered_by_prefix': 'Pokretač: ', 'amount_prefix': 'Količina: ', 'last_7_days': 'Poslednjih 7 dana',

      'choose_cat': 'Izaberi mačku.', 'choose_day': 'Izaberi bar jedan dan u sedmici.',
      'schedule_save_error': 'Greška pri čuvanju rasporeda.', 'connection_error_prefix': 'Greška pri povezivanju: ',
      'edit_schedule': 'Uredi raspored', 'cat_label': 'Mačka',
      'no_cats_add_first': 'Nemaš nijednu mačku — dodaj je prvo na ekranu za hranjenje.',
      'feeding_time': 'Vrijeme hranjenja', 'portion_amount': 'Količina obroka',
      'days_of_week': 'Dani u sedmici', 'add_schedule': 'Dodaj raspored',

      'log_weight_title': 'Zabilježi težinu', 'latest_entry': 'Zadnji unos',
      'average': 'Prosjek', 'maximum': 'Maksimum', 'log_todays_weight': 'Zabilježi današnju težinu',
      'food_trend_note': 'Zbir grama nahranjenih po danu, iz evidencije hranjenja.',
      'water_trend_note': 'Nivo vode u spremniku prema zadnjem senzorskom očitavanju tog dana.',
      'no_data_7_days': 'Nema podataka za posljednjih 7 dana',

      'feeder_status_title': 'Status hranilice', 'food_level_title': 'Nivo hrane u spremniku',
      'food_low_warning': 'Vrijeme je da dosuješ hranu u spremnik',
      'water_level_title': 'Nivo vode u posudi', 'water_low_warning': 'Vrijeme je da dosuješ vodu',
      'humidity': 'Vlažnost zraka', 'no_sensor_data': 'Nema još podataka sa senzora',
      'running_low': 'Ponestaje!',

      'camera_title': 'Kamera', 'connecting_camera': 'Povezivanje sa kamerom...',
      'pair_camera': 'Poveži kameru', 'check_wifi_range': 'Provjeri da je kamera u dometu WiFi mreže.',
      'pair_camera_explain': 'Uključi kameru na hranilici i pritisni dugme ispod da je upariš i počneš da nadgledaš svoju mačku uživo.',
      'start_pairing': 'Započni uparivanje', 'live_label': 'UŽIVO', 'monitoring_prefix': 'Nadgledanje: ',
      'video_simulation_note': 'Video prikaz je trenutno simulacija — poveži pravi video stream kad hardver kamere bude spreman.',
      'paired_online': 'Upareno • Online', 'remove': 'Ukloni',
      'default_camera_name': 'Kamera hranilice', 'camera_connected': 'Kamera povezana',

      'feed_now': 'Nahrani sada', 'feed_dialog_title': 'Nahrani mačku', 'feed_button': 'Nahrani',
      'fed_success_title': 'Nahranjeno! 🐾', 'fed_success_for_name': 'za',
      'feed_failed': 'Neuspješno hranjenje.', 'no_cats_to_feed': 'Prvo dodaj mačku da bi je mogao nahraniti.',
      'custom_amount': 'Drugo', 'custom_amount_hint': 'Unesi količinu',
      'custom_task_hint': 'Dodaj svoj zadatak...',
      'services_subtitle': 'Sve što ti treba za brigu o mački, na jednom mjestu',
      'notifications_info': 'Uključene u Android/iOS Settings za ovu app.',
      'about_app_body': 'IoT projekat za automatsko i ručno hranjenje mačaka.',
      'welcome_back': 'Dobrodošao nazad! 👋',
      'connection_error_title': 'Nema konekcije sa serverom',
      'connection_error_body': 'Provjeri adresu servera — dodirni za podešavanje',
    },
    'en': {
      'device': 'Devices', 'care': 'Care', 'services': 'Services', 'me': 'Me',
      'my_cats': 'My Cats', 'add': 'Add', 'server_address': 'Server Address',
      'notifications': 'Notifications', 'notifications_sub': 'Reminders and low-level alerts',
      'about_app': 'About', 'about_app_sub': 'Version, license, about the project',
      'language': 'Language', 'bosnian': 'Bosnian', 'english': 'English',
      'online': 'Online', 'food': 'Food', 'water': 'Water', 'temperature': 'Temperature',
      'tap_for_status': 'Tap for detailed status →', 'discover': 'Discover',
      'connect_camera': 'Connect a camera to the feeder', 'connect_camera_sub': 'Watch your cat live, from anywhere.',
      'coming_soon': 'Coming soon', 'not_connected': 'Not connected',
      'camera_not_connected': 'Camera not connected',
      'camera_explain': 'Live video needs an ESP32-CAM module and a streaming server, which aren\'t part of the hardware yet. Once connected, you\'ll pair the camera and watch your cat live here.',
      'understand': 'Got it',
      'feeder_name': 'CatFeeder Feeder',
      'feeding_schedule': 'Feeding schedule & history', 'feeding_schedule_sub': 'Set up automatic feeding and view history',
      'store': 'Store', 'store_sub': 'Food, accessories and equipment',
      'no_cats_yet': "You don't have any cats yet.", 'user': 'User',
      'dashboard': 'Dashboard', 'care_list': 'Care List', 'overview': 'Overview', 'edit': 'Edit',
      'weight': 'Weight', 'food_intake': 'Food intake', 'meals': 'Meals', 'total': 'Total',
      'water_level': 'Water level', 'current': 'Current', 'status': 'Status', 'low': 'Low',
      'ok': 'OK', 'trend_7d': '7-day trend',

      'coming_soon_snackbar': 'Coming soon.',
      'times_suffix': 'times', 'about_cat': 'About the cat', 'years_suffix': 'yrs',
      'male': 'Male', 'female': 'Female',
      'no_cat_dashboard': 'Add your first cat to see the dashboard.',
      'no_cat_care_list': 'Add your first cat to see the care list.',
      'todo': 'To-do', 'daily_progress': 'Daily progress', 'add_task': 'Add task',
      'eg_half_cup': 'e.g. 1/2 cup', 'cancel': 'Cancel', 'save': 'Save', 'delete': 'Delete',

      'edit_profile': 'Edit profile', 'add_cat_title': 'Add cat',
      'save_changes_failed': 'Failed to save changes.', 'add_cat_failed': 'Failed to add cat.',
      'delete_cat_q': 'Delete',
      'delete_cat_warning': 'This will permanently delete feeding history and schedules. This cannot be undone.',
      'delete_failed': 'Delete failed.',
      'cat_name_label': 'Cat name', 'eg_bella': 'e.g. Bella', 'gender_label': 'Gender',
      'age_label': 'Age', 'weight_kg_label': 'Weight (kg)', 'breed_label': 'Breed',
      'eg_domestic_shorthair': 'Domestic Shorthair', 'save_changes': 'Save changes',
      'delete_cat_button': 'Delete cat', 'unknown_breed': 'Unknown breed',
      'daily_goal_label': 'Daily food goal',
      'notif_feeding_title': 'Feeding time 🐾',
      'notif_feeding_body_needs': 'needs',
      'notif_food_low_title': 'Running low on food! 🍽️',
      'notif_water_low_title': 'Running low on water! 💧',
      'notif_level_food_word': 'Food level',
      'notif_level_water_word': 'Water level',
      'notif_level_body_suffix': 'dropped to',
      'notif_level_body_action': 'Time to refill.',
      'notif_schedule_channel_name': 'Feeding reminders',
      'notif_schedule_channel_desc': 'Reminds you when it\'s time for a scheduled feeding',
      'notif_alert_channel_name': 'Level alerts',
      'notif_alert_channel_desc': 'Warns you when food or water is running low',
      'version_label': 'Version', 'close_button': 'Close',
      'edit_name_title': 'Your name', 'your_name_hint': 'e.g. Asad',
      'welcome_subtitle': 'Caring for your cat, right at your fingertips.',
      'your_name_question': "What's your name?", 'continue_button': 'Continue',
      'logout': 'Log out', 'logout_confirm_title': 'Log out?',
      'logout_confirm_body': 'Your name will be cleared. Cats, schedules and the server address stay saved.',
      'create_account_subtitle': 'Create an account to get started.',
      'username_label': 'Username', 'password_label': 'Password',
      'password_hint_min': 'At least 6 characters.',
      'create_account_button': 'Create account', 'login_button': 'Log in',
      'have_account_question': 'Already have an account? Log in',
      'no_account_question': "Don't have an account? Create one",

      'server_url_invalid': 'Address must start with http:// or https://',
      'connection_success': 'Connection successful! Server is responding.',
      'connection_error_status': 'Server responded, but with an error',
      'connection_failed_prefix': 'Could not connect: ',
      'address_saved': 'Address saved and data refreshed. 🐾',
      'backend_address_title': 'Backend server address',
      'backend_address_sub': 'This is where the app looks for your .NET backend.',
      'test_connection': 'Test connection',
      'hide_help': 'Hide help', 'which_address': 'Which address should I use?',
      'help_emulator_label': '• Android Emulator (testing on a computer):',
      'help_real_phone_label': '• Real phone, same WiFi network as the computer:',
      'help_lan_ip_note': '(Find the LAN IP with "ipconfig" in a terminal, e.g. 192.168.1.50)',

      'unknown_cat': 'Unknown cat', 'error_reading_history_prefix': 'Error reading history: ',
      'delete_schedule_q': 'Delete schedule?', 'action_irreversible': 'This action cannot be undone.',
      'error_prefix': 'Error: ', 'activities_title': 'Activities',
      'history_tab': 'History', 'schedules_tab': 'Schedules', 'new_schedule': 'New schedule',
      'no_feedings_logged': 'No feedings logged',
      'no_feedings_logged_sub': "Once you feed your cat (manually or via a schedule), it'll show up here.",
      'no_schedules': 'No schedules',
      'no_schedules_sub': 'Schedule automatic feeding by day of the week and exact time.',
      'triggered_by_prefix': 'Triggered by: ', 'amount_prefix': 'Amount: ', 'last_7_days': 'Last 7 days',

      'choose_cat': 'Choose a cat.', 'choose_day': 'Choose at least one day of the week.',
      'schedule_save_error': 'Error saving schedule.', 'connection_error_prefix': 'Connection error: ',
      'edit_schedule': 'Edit schedule', 'cat_label': 'Cat',
      'no_cats_add_first': 'You have no cats — add one first on the feeding screen.',
      'feeding_time': 'Feeding time', 'portion_amount': 'Portion amount',
      'days_of_week': 'Days of the week', 'add_schedule': 'Add schedule',

      'log_weight_title': 'Log weight', 'latest_entry': 'Latest entry',
      'average': 'Average', 'maximum': 'Maximum', 'log_todays_weight': "Log today's weight",
      'food_trend_note': 'Sum of grams fed per day, from the feeding log.',
      'water_trend_note': "Water level in the tank from that day's last sensor reading.",
      'no_data_7_days': 'No data for the last 7 days',

      'feeder_status_title': 'Feeder status', 'food_level_title': 'Food level in tank',
      'food_low_warning': 'Time to refill the food tank',
      'water_level_title': 'Water level in bowl', 'water_low_warning': 'Time to refill the water',
      'humidity': 'Humidity', 'no_sensor_data': 'No sensor data yet',
      'running_low': 'Running low!',

      'camera_title': 'Camera', 'connecting_camera': 'Connecting to camera...',
      'pair_camera': 'Connect camera', 'check_wifi_range': 'Check that the camera is within WiFi range.',
      'pair_camera_explain': 'Turn on the feeder camera and press the button below to pair it and start watching your cat live.',
      'start_pairing': 'Start pairing', 'live_label': 'LIVE', 'monitoring_prefix': 'Monitoring: ',
      'video_simulation_note': 'The video feed is currently a simulation — connect a real video stream once the camera hardware is ready.',
      'paired_online': 'Paired • Online', 'remove': 'Remove',
      'default_camera_name': 'Feeder camera', 'camera_connected': 'Camera connected',

      'feed_now': 'Feed now', 'feed_dialog_title': 'Feed cat', 'feed_button': 'Feed',
      'fed_success_title': 'Fed! 🐾', 'fed_success_for_name': 'for',
      'feed_failed': 'Feeding failed.', 'no_cats_to_feed': 'Add a cat first before you can feed it.',
      'custom_amount': 'Custom', 'custom_amount_hint': 'Enter amount',
      'custom_task_hint': 'Add your own task...',
      'services_subtitle': 'Everything you need to care for your cat, in one place',
      'notifications_info': 'Enabled in Android/iOS Settings for this app.',
      'about_app_body': 'An IoT project for automatic and manual cat feeding.',
      'welcome_back': 'Welcome back! 👋',
      'connection_error_title': 'No connection to server',
      'connection_error_body': 'Check your server address — tap to configure',
    },
  };

  static String t(String key) => _values[locale.value]?[key] ?? _values['bs']![key] ?? key;
}
