name: iOS Unsigned Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        working-directory: CatFeeder # Promijeni ako se Flutter folder zove npr. CatFeederMobile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Unsigned iOS App
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r CatFeeder.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CatFeeder-IPA
          path: ${{ github.workspace }}/CatFeeder/build/ios/ipa/CatFeeder.ipa
